"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from '@/components/Nav'
import Header from "@/components/Header"
import TopLeftImg  from "@/components/TopLeftImg"
import { useRouter , usePathname } from 'next/navigation'
import Transition from "@/components/Transition"
import { AnimatePresence , motion } from 'framer-motion'
import { userAgent } from 'next/server'

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const router = useRouter()
  const pasth = usePathname()
  return (
    <html lang="en">
      <body className={inter.className}>
        <AnimatePresence mode='wait'>
          <motion.div key={pasth}>
            <Transition /> 
                <div className='page bg-site text-white bg-cover bg-no-repeat relative'>
            <Nav />
            <Header />
            <TopLeftImg />
            {children}
            </div>
          </motion.div>
        </AnimatePresence>
        </body>
    </html>
  )
}
