import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Nav from '@/components/Nav'
import Header from "@/components/Header"
import TopLeftImg  from "@/components/TopLeftImg"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='page bg-site text-white bg-cover bg-no-repeat relative'>
        <Nav />
        <Header />
        <TopLeftImg />
        {children}
        </div>
        </body>
    </html>
  )
}
